import {
    BackgroundImg,
    productA,
    productB,
    productC,
    productD,
    furnitureA,
    furnitureB,
    furnitureC,
    furnitureD,
    furnitureE,
} from '../../../public/assets/furniturePage'

export const categoriesHeading = [
    'Living Room Funiture',
    'Bedroom Furniture',
    'Office Furniture',
    'Dining Sets',
    'Kitchen Furniture',
    'Cabinets & Bookshelves',
];

export const mobileCategories = [
    {
        img: furnitureA,
        name: 'Living Room Funiture',
    },
    {
        img: furnitureB,
        name: 'Bedroom Furniture',
    },
    {
        img: furnitureC,
        name: 'Office Furniture',
    },
    {
        img: furnitureD,
        name: 'Dining Sets',
    },
    {
        img: furnitureD,
        name: 'Kitchen Furniture',
    },
    {
        img: furnitureE,
        name: 'Cabinets & Bookshelves',
    },
];

export const productDetails = [
    {
        id:11,
        img: productA,
        reviews: 2,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 40,
        sold: 20,
    },
    {
        id:12,
        img: productB,
        reviews: 0,
        description:"Blue, double sided",
        name: 'Sofa Chair',
        price: 120000.00,
        discount: 200000.00,
        available: 35,
        sold: 40,
    },
    {
        id:13,
        img: productC,
        reviews: 1,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 10,
        sold: 50,
    },
    {
        id:14,
        img: productD,
        reviews: 0,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 40,
        sold: 20,
    },
    {
        id:15,
        img: productA,
        reviews: 3,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 40,
        sold: 20,
    },
    {
        id:16,
        img: productB,
        reviews: 0,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 40,
        sold: 20,
    },
    {
        id:17,
        img: productA,
        reviews: 3,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 40,
        sold: 20,
    },
    {
        id:18,
        img: productB,
        reviews: 0,
        description:"Blue, double sided",
        name: 'Sliding Curtains',
        price: 80000.00,
        discount: 180000.00,
        available: 40,
        sold: 20,
    },
]